development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  database: yanit_d

testing:
  adapter: mysql2
  encoding: utf8 
  username: root
  password: root
  pool: 5
  host: localhost 
  database: yanit_t

production:
  adapter: mysql2
  encoding: utf8
  database: uni_inv_p_1
  pool: 5
  host: yanit_p

